<?xml version="1.0"?>
<root xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://www.ros.org/wiki/xacro/#interface">


  <xacro:property name="camera_tower_height" value="0.49" />
  <xacro:property name="camera_tower_width" value="0.03" />
  <xacro:property name="camera_tower_depth" value="0.03" />
  
  <xacro:macro name="camera_tower" params="name parent *origin">
  	<link name="${name}_link">
      <inertial>
        <mass value="0.5" />
        <origin xyz="0 0 ${(camera_tower_height/2) - camera_tower_height}" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz="0 0 ${camera_tower_height - (camera_tower_height/2)}" rpy="0 0 0" />
        <geometry>
          <box size="${camera_tower_depth} ${camera_tower_width} ${camera_tower_height}"/>
        </geometry>
        <material name="youBot/LightGrey" />
      </visual>

      <collision>
        <origin xyz="0 0 ${camera_tower_height - (camera_tower_height/2)}" rpy="0 0 0" />
        <geometry>
           <box size="${camera_tower_depth} ${camera_tower_width} ${camera_tower_height}"/>
        </geometry>
      </collision >
    </link>
    
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
  </xacro:macro>

</root>
